import type { SectionDefinition } from "@/lib/builder/generation/v2/types";

export const SECTION_DEFINITIONS: Record<SectionDefinition["id"], SectionDefinition> = {
  hero: {
    id: "hero",
    label: "Hero",
    purpose: "Open the page with a clear promise and primary CTA.",
    supportedIndustries: ["barbershop", "restaurant", "dental_clinic", "real_estate"],
    legacyType: "hero",
    requiredContentFields: ["headline", "subheadline", "ctaLabel", "ctaHref"],
    optionalContentFields: ["kicker"],
    visualVariants: ["A", "B", "C", "D"],
    conversionRole: "primary_cta",
    includeRules: {},
    promptGuidance: "Headline must feel like the business, not a generic category statement."
  },
  signature_services: {
    id: "signature_services",
    label: "Signature Services",
    purpose: "Show the core offers with specific benefit framing.",
    supportedIndustries: ["barbershop"],
    legacyType: "services",
    requiredContentFields: ["title", "items"],
    optionalContentFields: ["eyebrow"],
    visualVariants: ["A", "B", "C"],
    conversionRole: "education",
    includeRules: { minServices: 2 },
    promptGuidance: "Avoid generic benefits. Tie each service to the result the client cares about."
  },
  service_pricing: {
    id: "service_pricing",
    label: "Service Pricing",
    purpose: "Frame the offer as bookable service tiers when real prices or clear packages exist.",
    supportedIndustries: ["barbershop"],
    legacyType: "pricing",
    requiredContentFields: ["title", "plans"],
    optionalContentFields: [],
    visualVariants: ["A", "B", "C"],
    conversionRole: "pricing",
    includeRules: { minServices: 2 },
    promptGuidance: "Only use pricing when the content feels honest and specific enough to help a booking decision."
  },
  featured_dishes: {
    id: "featured_dishes",
    label: "Featured Dishes",
    purpose: "Show the dishes or categories that give the restaurant its identity.",
    supportedIndustries: ["restaurant"],
    legacyType: "pricing",
    requiredContentFields: ["title", "plans"],
    optionalContentFields: ["kicker"],
    visualVariants: ["A", "B", "C"],
    conversionRole: "menu",
    includeRules: {},
    promptGuidance: "Write dishes so they sound edible and specific, not like menu placeholders."
  },
  menu_preview: {
    id: "menu_preview",
    label: "Menu Preview",
    purpose: "Help guests understand the shape of the menu before they arrive.",
    supportedIndustries: ["restaurant"],
    legacyType: "services",
    requiredContentFields: ["title", "items"],
    optionalContentFields: [],
    visualVariants: ["A", "B", "C"],
    conversionRole: "menu",
    includeRules: {},
    promptGuidance: "Talk in categories and signatures if the full menu is unavailable."
  },
  treatments_grid: {
    id: "treatments_grid",
    label: "Treatments Grid",
    purpose: "Present treatments clearly so patients understand what the clinic does.",
    supportedIndustries: ["dental_clinic"],
    legacyType: "services",
    requiredContentFields: ["title", "items"],
    optionalContentFields: [],
    visualVariants: ["A", "B", "C"],
    conversionRole: "education",
    includeRules: { minServices: 2 },
    promptGuidance: "Treatments should sound reassuring and clear, not over-technical."
  },
  featured_listings: {
    id: "featured_listings",
    label: "Featured Listings",
    purpose: "Show the property categories or active briefs the agency is known for.",
    supportedIndustries: ["real_estate"],
    legacyType: "pricing",
    requiredContentFields: ["title", "plans"],
    optionalContentFields: [],
    visualVariants: ["A", "B", "C"],
    conversionRole: "listings",
    includeRules: {},
    promptGuidance: "Do not invent exact live listings if none exist. Use real market categories and buyer intent instead."
  },
  buyer_seller_services: {
    id: "buyer_seller_services",
    label: "Buyer and Seller Services",
    purpose: "Explain what help the agency provides on each side of the transaction.",
    supportedIndustries: ["real_estate"],
    legacyType: "services",
    requiredContentFields: ["title", "items"],
    optionalContentFields: [],
    visualVariants: ["A", "B", "C"],
    conversionRole: "education",
    includeRules: {},
    promptGuidance: "Make the process feel navigable and specific."
  },
  proof_grid: {
    id: "proof_grid",
    label: "Proof Grid",
    purpose: "Create trust without relying on fake testimonials.",
    supportedIndustries: ["barbershop", "restaurant", "dental_clinic", "real_estate"],
    legacyType: "services",
    requiredContentFields: ["title", "items"],
    optionalContentFields: [],
    visualVariants: ["A", "B", "C"],
    conversionRole: "proof",
    includeRules: {},
    promptGuidance: "Use credentials, review summaries, process discipline, or reputation cues instead of invented quotes."
  },
  review_summary: {
    id: "review_summary",
    label: "Review Summary",
    purpose: "Summarize the kind of feedback the business is known for without fabricating named customers.",
    supportedIndustries: ["barbershop", "restaurant", "dental_clinic", "real_estate"],
    legacyType: "testimonials",
    requiredContentFields: ["title", "items"],
    optionalContentFields: [],
    visualVariants: ["A", "B", "C"],
    conversionRole: "proof",
    includeRules: { requiresProof: true },
    excludeRules: { whenNoProof: true },
    promptGuidance: "Use labels like review summary or guest feedback. Never invent people."
  },
  brand_story: {
    id: "brand_story",
    label: "Brand Story",
    purpose: "Explain what the place feels like and what makes it distinct.",
    supportedIndustries: ["barbershop"],
    legacyType: "about",
    requiredContentFields: ["title", "body"],
    optionalContentFields: [],
    visualVariants: ["A", "B", "C"],
    conversionRole: "brand",
    includeRules: {},
    promptGuidance: "Describe the room, the pace, and the standard clients can expect."
  },
  atmosphere_story: {
    id: "atmosphere_story",
    label: "Atmosphere Story",
    purpose: "Translate the dining experience into a reason to visit.",
    supportedIndustries: ["restaurant"],
    legacyType: "about",
    requiredContentFields: ["title", "body"],
    optionalContentFields: [],
    visualVariants: ["A", "B", "C"],
    conversionRole: "brand",
    includeRules: {},
    promptGuidance: "Use atmosphere cues guests can picture before arriving."
  },
  clinic_reassurance: {
    id: "clinic_reassurance",
    label: "Clinic Reassurance",
    purpose: "Lower patient hesitation and make the clinic feel safe to contact.",
    supportedIndustries: ["dental_clinic"],
    legacyType: "about",
    requiredContentFields: ["title", "body"],
    optionalContentFields: [],
    visualVariants: ["A", "B", "C"],
    conversionRole: "trust",
    includeRules: {},
    promptGuidance: "Speak to clarity, calm appointments, and how treatment is explained."
  },
  neighborhood_expertise: {
    id: "neighborhood_expertise",
    label: "Neighborhood Expertise",
    purpose: "Show the agency understands the area rather than selling generic real estate help.",
    supportedIndustries: ["real_estate"],
    legacyType: "about",
    requiredContentFields: ["title", "body"],
    optionalContentFields: [],
    visualVariants: ["A", "B", "C"],
    conversionRole: "trust",
    includeRules: {},
    promptGuidance: "Talk about local buying patterns, neighborhoods, and property fit."
  },
  gallery_showcase: {
    id: "gallery_showcase",
    label: "Gallery Showcase",
    purpose: "Use imagery where the category genuinely benefits from it.",
    supportedIndustries: ["barbershop", "restaurant"],
    legacyType: "gallery",
    requiredContentFields: ["title"],
    optionalContentFields: [],
    visualVariants: ["A", "B", "C"],
    conversionRole: "brand",
    includeRules: {},
    promptGuidance: "Give the gallery a real framing title, not just gallery."
  },
  faq: {
    id: "faq",
    label: "FAQ",
    purpose: "Remove friction before the user reaches out.",
    supportedIndustries: ["barbershop", "dental_clinic"],
    legacyType: "faq",
    requiredContentFields: ["title", "items"],
    optionalContentFields: [],
    visualVariants: ["A", "B"],
    conversionRole: "education",
    includeRules: {},
    promptGuidance: "Answer the practical questions people ask before booking."
  },
  booking_cta: {
    id: "booking_cta",
    label: "Booking CTA",
    purpose: "Push the final booking action.",
    supportedIndustries: ["barbershop", "dental_clinic"],
    legacyType: "cta",
    requiredContentFields: ["title", "body", "ctaLabel", "ctaHref"],
    optionalContentFields: [],
    visualVariants: ["A", "B", "C"],
    conversionRole: "primary_cta",
    includeRules: {},
    promptGuidance: "CTA must sound like a real next step, not generic outreach."
  },
  reservation_cta: {
    id: "reservation_cta",
    label: "Reservation CTA",
    purpose: "Make reserving a table feel immediate and easy.",
    supportedIndustries: ["restaurant"],
    legacyType: "reservation",
    requiredContentFields: ["title", "body"],
    optionalContentFields: ["kicker"],
    visualVariants: ["A", "B"],
    conversionRole: "primary_cta",
    includeRules: {},
    promptGuidance: "Reservation copy should feel like a dining plan, not a generic form invite."
  },
  lead_cta: {
    id: "lead_cta",
    label: "Lead CTA",
    purpose: "Turn interest into property inquiries.",
    supportedIndustries: ["real_estate"],
    legacyType: "cta",
    requiredContentFields: ["title", "body", "ctaLabel", "ctaHref"],
    optionalContentFields: [],
    visualVariants: ["A", "B", "C"],
    conversionRole: "primary_cta",
    includeRules: {},
    promptGuidance: "Lead CTA must feel specific to viewing, valuation, or local advice."
  },
  contact_hours: {
    id: "contact_hours",
    label: "Contact and Hours",
    purpose: "Close the page with the practical contact details that help someone act.",
    supportedIndustries: ["barbershop", "restaurant", "dental_clinic", "real_estate"],
    legacyType: "contact",
    requiredContentFields: ["title", "body"],
    optionalContentFields: ["email", "phone", "address"],
    visualVariants: ["A", "B", "C"],
    conversionRole: "contact",
    includeRules: {},
    promptGuidance: "Include how, where, and when to reach the business."
  },
  payment_info: {
    id: "payment_info",
    label: "Payment and Insurance Info",
    purpose: "Reduce hesitation around treatment planning and payment questions.",
    supportedIndustries: ["dental_clinic"],
    legacyType: "services",
    requiredContentFields: ["title", "items"],
    optionalContentFields: [],
    visualVariants: ["A", "B", "C"],
    conversionRole: "trust",
    includeRules: {},
    promptGuidance: "Explain payment flexibility and insurance handling without making legal claims."
  },
  footer: {
    id: "footer",
    label: "Footer",
    purpose: "Close with brand and contact continuity.",
    supportedIndustries: ["barbershop", "restaurant", "dental_clinic", "real_estate"],
    legacyType: "footer",
    requiredContentFields: ["text"],
    optionalContentFields: [],
    visualVariants: ["A", "B"],
    conversionRole: "brand",
    includeRules: {},
    promptGuidance: "Keep the footer line concise and owned."
  }
};
