import {
  Bed,
  Building2,
  Calendar,
  Car,
  Clock,
  Dumbbell,
  Euro,
  HelpCircle,
  Home,
  Info,
  Mail,
  MapPin,
  MessageCircle,
  MessageSquare,
  Phone,
  Scissors,
  Sparkles,
  Stethoscope,
  Tag,
  Utensils,
  type LucideIcon,
} from "lucide-react";

export const QUICK_BUTTON_ICON_MAP: Record<string, LucideIcon> = {
  clock: Clock,
  phone: Phone,
  mail: Mail,
  "map-pin": MapPin,
  calendar: Calendar,
  utensils: Utensils,
  menu: MessageSquare,
  tag: Tag,
  euro: Euro,
  "message-circle": MessageCircle,
  car: Car,
  home: Home,
  building: Building2,
  stethoscope: Stethoscope,
  scissors: Scissors,
  dumbbell: Dumbbell,
  bed: Bed,
  sparkles: Sparkles,
  info: Info,
  "help-circle": HelpCircle,
};

export const QUICK_BUTTON_ICON_OPTIONS = Object.entries(QUICK_BUTTON_ICON_MAP).map(([key, Icon]) => ({
  key,
  Icon,
}));
